### ISSUE TITLE
IOMixin does not properly apply through prototypical inheritance

### ISSUE THREAD

**Issue by bfowle** [sinfo/ampersand-io-model#6]
I was attempting to use the demo example:

var mymodel =  new (IOModel.extend({props: {
  id: ['string'],
  thread: ['string'],
  source: ['string'],
  member: ['string']
}}))();

"mymodel" in this case includes: 
_cache: Object
_changed: Object
_definition: Object
_events: Object
_keyTree: KeyTreeStore
_previousAttributes: Object
_values: Object
  all: (...)
  attributes: (...)
  cid: "state1"
  collection: undefined
  id: (...)
  isState: (...)
  member: (...)
  parent: undefined
  source: (...)
  thread: (...)
__proto__: Surrogate

It does not include the ampersand-io-model functions: save/fetch/etc.

Stepping through the code, calling "new IOMixin()" includes the AmpersandIO extended object with these functions, but calling "new AmpersandIOModel()" -- IOMixin.call(this, ...) does not apply.

p.s. unit tests (called via 'npm test') also fail with these functions being 'undefined'.

Cheers~

**Comment by JGAntunes** [comment]
Hey @bfowle, thank you for the feedback, somehow I didn't know this was like this. The issue with the prototype chain should be solved I think, but this repo definitely needs further testing and some proper documentation which I will work on as soon as I have some time.

**Comment by bfowle** [comment]
Hello @JGAntunes thanks for the quick reply. That seemed to have fix it. :+1: 
This is a great little project that will come in handy for many, I believe. 
Cheers~

**Comment by JGAntunes** [comment]
@bfowle glad I could help. I will publish this to the npm registry asap.

Yeah that's what we've though with this. We are actually using it at SINFO on production to manage our notification system (a previous version, not this latest release).

Thank you once again!
