### ISSUE TITLE
Handle multiple socket namespaces across unique objects

### ISSUE THREAD

**Issue by bfowle** [sinfo/ampersand-io-model#7]
If setting up multiple namespaces to listen for certain event types-- creating unique ampersand-io-model objects on each ns seems to only receive messages on the first instantiated object. It does however properly send messages from the client->server on each individual ns.

Client-side:
fooModel = new MyObject({...}, {socket: '/foo'})
barModel = new MyObject({...}, {socket: '/bar'})

Server-side:
io.of('/foo').emit('model-update', {...})
io.of('/bar').emit('model-update', {...})

From a server-side emit(), any message on a client-side object under the /foo ns will be received. If commenting out the "fooModel" in this case, objects under the /bar ns will then be received properly.

From the client-side, when a model update / emit() happens, the server DOES receive them properly, as expected.

**Comment by bfowle** [comment]
I should also note: this happens without multiple namespaces as well. So perhaps is a more general issue.
If instantiating more than one model object (that listens on the default '/' namespace), it only transmits to the first-created object.
My use case is: having a query and an answer model listening over individual sockets; both use the inner ampersand-io-model event: 'model-update'. Query builds in real time with client-side interactions; answers stream back as the server retrieves them and transmits them back to the client.

**Comment by bfowle** [comment]
From what I can tell about Ampersand -- each model object has a unique identifier (generally: 'id').

In the case of having multiple ampersand-io-model objects: sending a socket.io event with "socket.emit" should include the ampersand-like data model in it:
e.g. { data: { id: "someId", foo: "bar"} } 

On the client-side, a custom callback function on the "model-update" can do a sanity check that the "this.id === data.id" that was sent, and set if it matches.

This does work across tabs, but still-- only the first instantiated object is working properly.

**Comment by JGAntunes** [comment]
Hey @bfowle sorry about the delay getting back to you. Have been around a lot of stuff recently

So as for the first issue it's a known one, I'll probably take a look at it today or tomorrow as it seems still an issue with the inheritance which is making the extended module to be tied with the original prototype somehow... I also need to do a bunch of testing one this.

As for the second one... For now you can always override the existing methods but, if I understood you correctly, sending the model id would be only for sanity-check on the front-end right? Why would you need it in particular? Do you have any particular use case? I mean if you send a `socket.emit` via one socket in one tab the response should come to that same socket from the back end.
As for the single-user-multi-connect definitley agree there's some progress to be done here, I actually have flagged a couple of issues and error which need to be taken care of.

**Comment by bfowle** [comment]
I believe the second case was an artifact of the first coupled with a somewhat strange usage on my part. The initial issue would still be interesting to see working, as I can see quite a few use cases for this. Thanks!

**Comment by JGAntunes** [comment]
@bfowle the problem should be solved I think, gonna publish this and `ampersand-io` to npm. Check if everything looks good.
